<a href="https://colab.research.google.com/github/23Aditya/Keras/blob/main/Keras_Binary_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("/content/data.csv")

In [3]:
data

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0      842302         M  ...                  0.11890          NaN
1      842517         M  ...                  0.08902          NaN
2    84300903         M  ...                  0.08758          NaN
3    84348301         M  ...                  0.17300          NaN
4    84358402         M  ...                  0.07678          NaN
..        ...       ...  ...                      ...          ...
564    926424         M  ...                  0.07115          NaN
565    926682         M  ...                  0.06637          NaN
566    926954         M  ...                  0.07820          NaN
567    927241         M  ...                  0.12400          NaN
568     92751         B  ...                  0.07039          NaN

[569 rows x 33 columns]

In [4]:
data.drop([data.columns[0],data.columns[32]],axis=1,inplace=True)

In [5]:
data

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0           M        17.99  ...          0.4601                  0.11890
1           M        20.57  ...          0.2750                  0.08902
2           M        19.69  ...          0.3613                  0.08758
3           M        11.42  ...          0.6638                  0.17300
4           M        20.29  ...          0.2364                  0.07678
..        ...          ...  ...             ...                      ...
564         M        21.56  ...          0.2060                  0.07115
565         M        20.13  ...          0.2572                  0.06637
566         M        16.60  ...          0.2218                  0.07820
567         M        20.60  ...          0.4087                  0.12400
568         B         7.76  ...          0.2871                  0.07039

[569 rows x 31 columns]

In [6]:
data['diagnosis'].replace(to_replace=['B','M'],value=[0,1],inplace=True)

In [7]:
data = np.array(data) 

In [8]:
np.random.shuffle(data)

In [9]:
data

array([[ 1.     , 16.35   , 23.29   , ...,  0.2248 ,  0.4824 ,  0.09614],
       [ 0.     , 12.85   , 21.37   , ...,  0.05601,  0.2488 ,  0.08151],
       [ 0.     , 14.41   , 19.73   , ...,  0.1021 ,  0.2272 ,  0.08799],
       ...,
       [ 0.     , 10.26   , 12.22   , ...,  0.06696,  0.2937 ,  0.07722],
       [ 1.     , 17.46   , 39.28   , ...,  0.2066 ,  0.2853 ,  0.08496],
       [ 0.     , 13.17   , 18.22   , ...,  0.1045 ,  0.2235 ,  0.06925]])

In [10]:
Y = data[:,0]

In [11]:
Y

array([1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1.,
       1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
       0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 1., 0., 0.

In [12]:
X = data[:,1:]

In [13]:
X

array([[1.635e+01, 2.329e+01, 1.090e+02, ..., 2.248e-01, 4.824e-01,
        9.614e-02],
       [1.285e+01, 2.137e+01, 8.263e+01, ..., 5.601e-02, 2.488e-01,
        8.151e-02],
       [1.441e+01, 1.973e+01, 9.603e+01, ..., 1.021e-01, 2.272e-01,
        8.799e-02],
       ...,
       [1.026e+01, 1.222e+01, 6.575e+01, ..., 6.696e-02, 2.937e-01,
        7.722e-02],
       [1.746e+01, 3.928e+01, 1.134e+02, ..., 2.066e-01, 2.853e-01,
        8.496e-02],
       [1.317e+01, 1.822e+01, 8.428e+01, ..., 1.045e-01, 2.235e-01,
        6.925e-02]])

In [14]:
X_dash = (X - np.mean(X,axis=0))/np.std(X,axis=0)

In [15]:
X_dash

array([[ 0.6312807 ,  0.93090865,  0.70150892, ...,  1.67787627,
         3.11138732,  0.67575061],
       [-0.36276899,  0.48411176, -0.38467666, ..., -0.8922211 ,
        -0.66774819, -0.1349828 ],
       [ 0.08029316,  0.10247275,  0.16727203, ..., -0.19042723,
        -1.0171888 ,  0.22411169],
       ...,
       [-1.09836575, -1.64515466, -1.07996724, ..., -0.72548986,
         0.05863531, -0.37271666],
       [ 0.94653646,  4.65188898,  0.88274581, ...,  1.4007522 ,
        -0.07725826,  0.05620177],
       [-0.27188444, -0.24891439, -0.31671283, ..., -0.15388339,
        -1.07704668, -0.81438072]])

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X,X_test,Y,Y_test = train_test_split(X_dash,Y,test_size=0.10,random_state=42)

In [18]:
X.shape

(512, 30)

In [19]:
X_test.shape

(57, 30)

In [20]:
Y.shape

(512,)

In [21]:
Y_test.shape

(57,)

In [22]:
X_train,X_cv,Y_train,Y_cv = train_test_split(X,Y,test_size=0.15,random_state=42)

In [23]:
X_train.shape

(435, 30)

In [24]:
Y_train.shape

(435,)

In [25]:
X_cv.shape

(77, 30)

In [26]:
Y_cv.shape

(77,)

In [27]:
from keras.layers import InputLayer,Dense,BatchNormalization
from keras.models import Sequential
from keras.losses import binary_crossentropy
from keras.regularizers import l2

In [28]:
def build_network():

  network = Sequential()
  network.add(InputLayer(input_shape=(X_train.shape[1],)))
  network.add(Dense(units=X_train.shape[1],activation="relu",kernel_initializer="glorot_normal",kernel_regularizer=l2(0.1)))
  network.add(BatchNormalization())
  network.add(Dense(units=1,activation="sigmoid",kernel_initializer="glorot_normal",kernel_regularizer=l2(0.1)))

  return network

In [34]:
network = build_network()

In [35]:
network.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [36]:
performance_history = network.fit(x=X_train,y=Y_train,batch_size=5,epochs=100,validation_data=(X_cv,Y_cv))

Epoch 1/100
87/87 [==============================] - 1s 4ms/step - loss: 2.9258 - accuracy: 0.8483 - val_loss: 2.3438 - val_accuracy: 0.8961
Epoch 2/100
87/87 [==============================] - 0s 2ms/step - loss: 1.8646 - accuracy: 0.8851 - val_loss: 1.5060 - val_accuracy: 0.9221
Epoch 3/100
87/87 [==============================] - 0s 2ms/step - loss: 1.2801 - accuracy: 0.8851 - val_loss: 1.0181 - val_accuracy: 0.9610
Epoch 4/100
87/87 [==============================] - 0s 3ms/step - loss: 0.8935 - accuracy: 0.8874 - val_loss: 0.7236 - val_accuracy: 0.9610
Epoch 5/100
87/87 [==============================] - 0s 2ms/step - loss: 0.6952 - accuracy: 0.9057 - val_loss: 0.5216 - val_accuracy: 0.9740
Epoch 6/100
87/87 [==============================] - 0s 2ms/step - loss: 0.5231 - accuracy: 0.9080 - val_loss: 0.4026 - val_accuracy: 0.9870
Epoch 7/100
87/87 [==============================] - 0s 2ms/step - loss: 0.4481 - accuracy: 0.9103 - val_loss: 0.3241 - val_accuracy: 0.9870
Epoch 8/100
8

In [37]:
network.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 30)                930       
                                                                 
 batch_normalization_1 (Batc  (None, 30)               120       
 hNormalization)                                                 
                                                                 
 dense_3 (Dense)             (None, 1)                 31        
                                                                 
Total params: 1,081
Trainable params: 1,021
Non-trainable params: 60
_________________________________________________________________


In [38]:
network.evaluate(x=X_test,y=Y_test)

2/2 [==============================] - 0s 8ms/step - loss: 0.1132 - accuracy: 0.9825


[0.11319027096033096, 0.9824561476707458]